---

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - additional_dependencies:
          - flake8-bugbear
          - flake8-pyproject
          - flake8-simplify
        id: flake8

exclude: |
  (?x)^(
    readme\.md
  )$

...
